from .__meta__ import __version__

# from janis_pipelines.alignment.alignment import BwaAlignment

from janis_pipelines.wgs_germline.wgsgermline import WGSGermlineMultiCallers
from janis_pipelines.wgs_germline_gatk.wgsgermlinegatk import WGSGermlineGATK

from janis_pipelines.wgs_somatic.wgssomatic import WGSSomaticMultiCallers
from janis_pipelines.wgs_somatic_gatk.wgssomaticgatk import WGSSomaticGATK
